### PR TITLE
Fix index vs ID core bug

### LINKED ISSUE #154: mesh_plot
Hi I'm new to adcircpy. I tried to follow example1, but added some mesh plot part,

    # open mesh file
    mesh = AdcircMesh.open(MESH_DIRECTORY / 'fort.14', crs=4326)
    print (mesh)
    fig,ax = plt.subplots(1,1,figsize=(10,10))
    ax = mesh.make_plot()
    ax.triplot(mesh.triangulation, color='k', linewidth=0.05)
    #ax.scatter(mesh.x[indexes], mesh.y[indexes], edgecolor='r', facecolor='none')
    plt.savefig('testmesh.png')
    plt.close()

The mesh.make_plot() line always gave me the following error,
ValueError: triangles max element is out of bounds

Please help.
Alex

### LINKED ISSUE #162: Access to land boundaries gives an error
An access to land boundaries of an AdcircMesh instance appears to have an issue.

```
from adcircpy import AdcircMesh
f14file = 'path/to/fort.14'
mesh = AdcircMesh.open(f14file, crs='EPSG:4326)
mesh.land_boundaries
```
gives
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[20], line 1
----> 1 mesh.land_boundaries

File d:\Python\Python38\lib\site-packages\adcircpy\mesh\fort14.py:285, in Fort14.land_boundaries(self)
    283 @property
    284 def land_boundaries(self):
--> 285     return self.boundaries.land

File d:\Python\Python38\lib\site-packages\adcircpy\mesh\fort14.py:150, in Fort14Boundaries.land(self)
    147 @property
    148 def land(self):
    149     if not hasattr(self, '_land'):
--> 150         self._land = LandBoundaries(self._mesh, self._aggregate_boundaries('0'))
    151     return self._land

File d:\Python\Python38\lib\site-packages\adcircpy\mesh\fort14.py:189, in Fort14Boundaries._aggregate_boundaries(self, endswith)
    187         continue
    188     if ibtype.endswith(endswith):
--> 189         for bdata in list(_boundaries.values()):
    190             boundaries.update({len(boundaries) + 1: {'ibtype': ibtype, **bdata,}})
    191 return boundaries

AttributeError: 'list' object has no attribute 'values'
```

while `mesh.ocean_boundaries` seems to be working.

### PR DESCRIPTION
**Pull request by SorooshMani-NOAA**
Fixes #154 The following issues are addressed
- Plotting triangles fails due to difference between ID vs index of the triangles. The index needs to be passed to `matplotlib`
- The shape of the values vs grid is also an issue

### CODE REVIEW

**Comment by krober10nd** [comment]
This looks good although now there's an issue with the installation of HDF5?

**Comment by SorooshMani-NOAA** [comment]
Thank you for reviewing. I'll need to figure out the automated test issues before merging. I mainly needed another set of eyes to check my changes in the code since I'm not a power ADCIRCPy user.

**Comment by SorooshMani-NOAA** [comment]
As discussed in the linked issues for this pull request specifically in #154 and more in #162, many of the changes needed for fixing the issues were related to pull request #121. I'm adding this as reference here since the changes might have other unforeseen impacts as they are related to the underlying index vs ID of nodes, and how these concepts were missed in #121

**Comment by SorooshMani-NOAA** [comment]
In #121 buggy references have been added for `fort.15` as well (see `blame` for `fort.15` files). The tidal constituents are 1 node off, e.g. instead of constituents being written for node ID 75 to node ID 1, they are written for node ID 76 to node ID 2.

**Comment by SorooshMani-NOAA** [comment]
@saeed-moghimi-noaa @pvelissariou1 @WPringle @krober10nd, I'm tagging everyone relevant on this pull request because it involves changes in the `adcircpy` code that fix a fundamental set of bugs. Here's how I would describe the issue and what I did:

As you know the node numbers in ADCRIC input files is 1-based (i.e. it starts from 1 not 0); in Python however, arrays are 0-based. To accommodate for this discrepancy, `adcircpy` used the terms ID (for 1-based indexing) and index (for 0-based indexing). As a side note let me also mention that using ID vs index makes the concept more general, such that the IDs could be just an array of unique numbers without any specification on the starting number or whether the numbers are continuous or not, so it's a very good generalization to make.

This concept was introduced from the start (or very early in the process) in `adcircpy`, however in #121 the core code was "revamp"ed such that it uses more of `pandas.DataFrame` vs custom objects for `Nodes`, etc. Unfortunately during the same merge, some confusion about ID vs index was introduced into the code. This introduced a bug in writing `fort.15` file's tidal constituents. However, the automated test errors were ignored and even the automated test reference files were updated with the new wrong ones! The issue is that now the tidal constituents are 1 node off; for example, instead of constituents being written for node ID 75 to node ID 1, they are written for node ID 76 to node ID 2 (also note that the node 76 might **not** even be in the open ocean boundary!). Other than that it started breaking `AdcircMesh.make_plot` (#154) and `AdcircMesh.land_boundaries` and `AdcircMesh.land_boundaries.gdf` (#162), but since there were no tests for these, they were also missed.

Now thanks to the people who started using `adcircpy` in their workflow, we noticed these bugs which lead us to find the source of the core bug in `adcircpy`. I fixed the parts of the code that I noticed, and also updated the automated test reference files. However I'm not sure if this might affect other parts of the code that I didn't touch, since the core bugs were compensated for by adding more buggy code in some other parts of the code (I tried to fix whatever I detected).

That's why before merging, I'd like another sets of eyes to check the changes. My current plan is to merge sometime before mid-week next week if I don't receive any feedback.

**Comment by SorooshMani-NOAA** [comment]
I merge this today since I didn't receive any feedback, please create new tickets/issues if you notice any issues with indexing for mesh nodes or boundaries. Thanks

**Pull request merged**
