### PR TITLE
Feature/wind swath

### PR DESCRIPTION
**Pull request by WPringle**
Adding method to extract `wind_swath` from the `BestTrackForcing` class. 

User selects the desired isotach (34-kt, 50-kt, 64-kt) to extract as a shapely Polygon.

Usage:
```
    # get the ATCF best track file
    cyclone = BestTrackForcing(
                storm,
                start_date=start_date,
                end_date=end_date,
    )

    swath = cyclone.get_wind_swath(isotach=64, plot_swath=True)
```

Example outputs:
Hurricane Florence 34-kt (5 days from 2018-09-11 00:00):
image
 
Hurricane Matthew 34-kt (5 days from 2016-10-05 00:00):
image

Hurricane Florence 64-kt (5 days from 2018-09-11 00:00):
image

### CODE REVIEW

**Comment by jreniel** [comment]
Thanks William, this is a really cool feature! Let me have some time to look closely at your code, comment if there's anything that could be optimized, and then we'll merge. Thanks again!

**Comment by jreniel** [comment]
~Can you push this commit to a branch in the adcircpy repo, so I can checkout without having to clone your fork separately, and then we can do joint pushes to a branch on this repo.~
I figured out how to fetch from a fork without recloning.

**Comment by krober10nd** [comment]
Could also represent the swaths as the intersection of many signed distance functions. For example, you could perturb a bunch of circles in the quadrant directions to get the swath at a given time interval. 

This approach would bypass the `alphashape` dependency and be the exact swath in accordance with NHC.

**Comment by WPringle** [comment]
That's exactly what is happening to get the `swath` at first. 

I suppose the adjustment by `alphashape` could be an optional thing. 

So user can ask to return either `swath_alpha` or `swath` (or both).

**Comment by WPringle** [comment]
@zacharyburnettNOAA 
FYI, this is what I got for the Florence 64-kt example, for `swath.convex_hull` (plotted in black) of the MultiPolygon `swath` (plotted in colors):
image

It's not perfectly tight around the individual polygons, which lead me to the complex `alphashape` logic (but does seem to work).

**Comment by jreniel** [comment]
> @zacharyburnettNOAA
> FYI, this is what I got for the Florence 64-kt example, for `swath.convex_hull` (plotted in black) of the MultiPolygon `swath` (plotted in colors):
> image
> 
> It's not perfectly tight around the individual polygons, which lead me to the complex `alphashape` logic (but does seem to work).

I'm actually working on an alternate version, because I've always felt that there's a better method to compute the swaths (using cyclinc interpolation). I want to present that alternate method to you before we merge, so we can discuss it.

**Comment by ghost** [comment]
> @zacharyburnettNOAA
> FYI, this is what I got for the Florence 64-kt example, for `swath.convex_hull` (plotted in black) of the MultiPolygon `swath` (plotted in colors):
> image
> 
> It's not perfectly tight around the individual polygons, which lead me to the complex `alphashape` logic (but does seem to work).

@WPringle This might be a bit more expensive, but I was thinking an iterative spatial merge would give us the results we want. What we actually want is for the individual radii to be connected in a smooth path that looks like a forecast cone (as it gets wider over the length of the track), and we are making the assumption that the storm will grow or shrink in a linear fashion in the time periods between those points. I don't think an alpha shape is the right call here because this isn't an instantaneous snapshot of several storms but *one* storm over several points in time.

Could you perhaps try a set of iterative convex hulls over each pair of radii? For instance, if you have polygons `a, b, c, d, e`, make a convex hull of polygons `a, b`, then a convex hull of `b, c`, then of `c, d`, and finally one of `d, e`. Now, all the convex hulls should be overlapping (by nature of their creation) and you can then dissolve them all together to get one big hull. That way, we wouldn't need `alphashape` at all. 

I'll work with with the code to figure out a good implementation of this to give an example.

**Comment by WPringle** [comment]
@zacharyburnettNOAA Yeah what you mentioned could work. I don't think that would be very expensive either.

**Comment by WPringle** [comment]
**Note:** Where forecast GIS files are kept: https://ftp.nhc.noaa.gov/atcf/gis/fst/

**Comment by jreniel** [comment]
Doing what I was thinking is more difficult than I thought, so I'm not going to continue trying.
We can merge this whenever you are ready.

**Comment by WPringle** [comment]
I think @zacharyburnettNOAA may be working on something. Let's wait to see.

**Comment by ghost** [comment]
how's this?
image

**Comment by WPringle** [comment]
yeah that looks perfect! If you can try few different storms and isotach values to make sure it always runs then I think we can go with that.

**Comment by ghost** [comment]
> yeah that looks perfect! If you can try few different storms and isotach values to make sure it always runs then I think we can go with that.

sure thing, what storms / isotachs / start and end times did you use for your plots above?

EDIT: oh wait, lol I can't read. I just realized you labeled the plots

**Comment by ghost** [comment]
fd455a3
image
image
image

**Comment by WPringle** [comment]
Cool, maybe give user option to output the `polygons` as well as or instead of `swath` as well?

**Comment by ghost** [comment]
> Cool, maybe give user option to output the `polygons` as well as or instead of `swath` as well?

okay, I added a new method `.isotachs()` (ddfba3a)

**Pull request merged**
