### PR TITLE
add type hints + reorder setters to be after properties + use native timedelta methods

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by krober10nd** [comment]
While we're reformatting here, is it possible to control the precision of station outputs? The default locations and precision of the station coordinate can lead to some issues with recording.

**Comment by krober10nd** [comment]
In fact this option could be useful across the board

**Comment by jreniel** [comment]
> In fact this option could be useful across the board

But it is dangerously overcomplicated to implement in practice. Perhaps the user should do pre-processing on their local data to adjust the precision of the values before passing to adcircpy? I'm just looking at it from a diff perspective, because I think I understand your thinking in a way. But maybe those details are best left to the judgement of the users?

**Comment by krober10nd** [comment]
I understand. Well what I was thinking was to pass a f-string to the writer methods as an option kwarg to control the formatting of floats. But yea for my client/application I just modified the codes in certain places (rnday, station output locations, and recording start and end times)

**Comment by ghost** [comment]
ok, is this good to merge then?

**Comment by krober10nd** [comment]
I guess. It's a little annoying that station outputs do not preserve the same numerical precision as they are when you load them in.

**Comment by jreniel** [comment]
> I guess. It's a little annoying that station outputs do not preserve the same numerical precision as they are when you load them in.

That's probably an easy fix. In practice the outputs files should not truncate the precision provided by the users.

**Comment by jreniel** [comment]
> I guess. It's a little annoying that station outputs do not preserve the same numerical precision as they are when you load them in.

Actually, could you refresh my memory on what you mean by this? Are we talking about RNDAY or something else?

**Comment by krober10nd** [comment]
Station output locations. The RNDAY is another issue.

**Comment by jreniel** [comment]
Based on this: https://github.com/jreniel/adcircpy/blob/update/miscellaneous/adcircpy/fort15.py#L214

It should be writing at the same precision as input by the user. Can you show some screenshots of the problem so we can take care of it before merging this one?

**Comment by krober10nd** [comment]
Okay 

with `output_stations.txt` (I truncated it because you can get the point). I tried with an older version and it rounded to the nearest second digit after the decimal. Maybe this changed recently. Four digits is fine although why is it rounding?

```
  -74.0136131626,40.6998053924
  -71.9726010621,41.05437953680001
  -74.9649491735,38.9631746587
  -74.1041333575,39.7607985049
  -74.4224425414,39.3436431356
  -74.0090328775,40.4661722475
  -74.1464335145,40.6396053541
  -73.1721656353,41.1550337951
  -74.02627106850001,40.7350466
```

```
 from datetime import datetime, timedelta
 
 import numpy as np
 from adcircpy import AdcircMesh, AdcircRun
 
 station_file = "output_stations.txt"
 
 mesh = AdcircMesh.open("fort.14", crs=4326)
 
 mesh.import_nodal_attributes("fort.13", enable=True)
 
 duration = timedelta(days=5)
 start_date = datetime(2015, 12, 14)
 end_date = start_date + duration
 
 driver = AdcircRun(mesh, start_date, end_date)
 
 driver.set_elevation_stations_output(sampling_rate=timedelta(minutes=6))
 stations = np.loadtxt(station_file, dtype=float, delimiter=",")
 for idx, sta in enumerate(stations):
     driver.add_elevation_output_station(f"Station_{idx}", sta)
 
 driver.write("test/", overwrite=True)
```

produces a fort.15 with this

```
 51                                                              ! NSTAE                               - TOTAL NUMBER OF ELEVATION RECORDING STATIONS
 -74.0136 40.6998                                                ! Station_0
 -71.9726 41.0544                                                ! Station_1
 -74.9649 38.9632                                                ! Station_2
 -74.1041 39.7608                                                ! Station_3
 -74.4224 39.3436                                                ! Station_4
 -74.009 40.4662                                                 ! Station_5
 -74.1464 40.6396                                                ! Station_6
 -73.1722 41.155                                                 ! Station_7
....
```

**Comment by jreniel** [comment]
There's another API braking change that was done here that needs fixing. It was supposed to be that you could pass any fort.15 containing the stations and it would load them, but some changes to the parsers broke the stations loading.

**Comment by krober10nd** [comment]
It would also be nice to have a bit more control over the `Driver.write` method (i.e., restrict which files actually get written).

**Comment by jreniel** [comment]
> It would also be nice to have a bit more control over the `Driver.write` method (i.e., restrict which files actually get written).

That is already implemented, set to `False` the kwarg on write() for any output you don't want written.

**Comment by jreniel** [comment]
The "correct" way of importing the stations would be that your `output_stations.txt` matches the formatting of a fort.15.
The first line (NOUTE, etc...) indicates to which variable this list will get imported. In this case it will get imported to those three.
You can create multiple lists for diff variables, or you can just use the same list with all the variables listed first.
```
NOUTE NOUTV NOUTM
9
-74.0136131626 40.6998053924
-71.9726010621 41.05437953680001
-74.9649491735 38.9631746587
-74.1041333575 39.7607985049
-74.4224425414 39.3436431356
-74.0090328775 40.4661722475
-74.1464335145 40.6396053541
-73.1721656353 41.1550337951
-74.02627106850001 40.7350466
```
now with the following you should get what you were looking for:
```python
from datetime import datetime, timedelta
 
import numpy as np
from adcircpy import AdcircMesh, AdcircRun

mesh = AdcircMesh.open('fort.14', crs='epsg:4326')
duration = timedelta(days=5)
start_date = datetime(2015, 12, 14)
end_date = start_date + duration
driver = AdcircRun(mesh, start_date, end_date)
driver.import_stations("output_stations.txt")
driver.set_elevation_stations_output(sampling_rate=timedelta(minutes=6))
driver.write("test/", overwrite=True)

```

**Comment by krober10nd** [comment]
Okay is it possible to put some example showing that on the readme? That's not obvious at all.

**Comment by jreniel** [comment]
> Okay is it possible to put some example showing that on the readme? That's not obvious at all.

I'll leave that up to you, or for the prospective users to figure it out.

**Comment by jreniel** [comment]
By the way, what you were doing before is also correct. Either way is fine, but the idea of the `import_stations` method is to be able to recycle stations from fort.15 files and to be able to structure different stations for different variables on a single file.

Let me know if you think this is ready for merge.

**Comment by jreniel** [comment]
Another trick is that, if you add the coops ID for the stations, the adcircpy outputs post processing scripts will be able to download the data and plot it for you
```
NOUTE NOUTV NOUTM
1
-74.0136131626 40.6998053924    !     12345678    (coops id)
```

**Comment by krober10nd** [comment]
Thanks Jaime. Then this PR lgtm

**Review by krober10nd — APPROVED** [review]

**Comment by ghost** [comment]
> The "correct" way of importing the stations would be that your `output_stations.txt` matches the formatting of a fort.15.
> The first line (NOUTE, etc...) indicates to which variable this list will get imported. In this case it will get imported to those three.
> You can create multiple lists for diff variables, or you can just use the same list with all the variables listed first.
> 
> ```fortran
> NOUTE NOUTV NOUTM
> 9
> -74.0136131626 40.6998053924
> -71.9726010621 41.05437953680001
> -74.9649491735 38.9631746587
> -74.1041333575 39.7607985049
> -74.4224425414 39.3436431356
> -74.0090328775 40.4661722475
> -74.1464335145 40.6396053541
> -73.1721656353 41.1550337951
> -74.02627106850001 40.7350466
> ```

I was under the impression that this ^ is not correct or valid `fort.15` formatting. 

I implemented the new parser to accept the following:
```fortran
9 ! NOUTE NOUTV NOUTM
-74.0136131626 40.6998053924
-71.9726010621 41.05437953680001
-74.9649491735 38.9631746587
-74.1041333575 39.7607985049
-74.4224425414 39.3436431356
-74.0090328775 40.4661722475
-74.1464335145 40.6396053541
-73.1721656353 41.1550337951
-74.02627106850001 40.7350466
```
```fortran
397                                                             ! NSTAE NOUTE NOUTV
-64.7033 32.3734                                                ! 2695540
-66.9826 44.9045                                                ! 8410140
-67.1085 44.8711                                                ! 8410714
-67.125 44.9199                                                 ! 8410715
-67.1407 45.1301                                                ! 8410834
-67.1494 44.8227                                                ! 8410864
-67.1872 44.6494                                                ! 8411060
0                                                               ! NOUTM
```
I implemented the new parser because it appeared that the old one ran through the entire file multiple times unnecessarily, so I wanted to cut down on the importing time because that was a big hurdle in my ensemble runs.

**Comment by jreniel** [comment]
> I implemented the new parser because it appeared that the old one ran through the entire file multiple times unnecessarily, so I wanted to cut down on the importing time because that was a big hurdle in my ensemble runs.

If you want to import something custom, you can import the stations just like this example:
```python
stations = np.loadtxt(station_file, dtype=float, delimiter=",")
 for idx, sta in enumerate(stations):
     driver.add_elevation_output_station(f"Station_{idx}", sta)
```

It's going through the file as many times as variables are requested. You can optimize the parser, but you should have kept the formatting which is exactly the same as a fort.15, so that any fort.15 can be imported. Your implementation broke the fort.15 importing, which is important (hence an API breaking change).

**Comment by jreniel** [comment]
From the ADCIRC documentation:
image

On a real fort.15:
```
-5 0.5 1 36                                                     ! NOUTE TOUTSE TOUTFE NSPOOLE         - ELEV STATION OUTPUT INFO (UNIT 61)
1                                                               ! NSTAE                               - TOTAL NUMBER OF ELEVATION RECORDING STATIONS
-72.5772 40.823                                                 ! 8512769                            
```
Note that the actual values of the NOUTE part are ignored, all the parser is looking for is the keyword NOUT*, and it will import each one individually, which is the part that could be optimized, but the ability to read a fort.15 directly should not be removed.
ref: https://github.com/jreniel/adcircpy/blob/main/tests/data/reference/test_best_track_run/fort.15.hotstart#L676-L678

**Comment by jreniel** [comment]
@zacharyburnettNOAA Do you want to give another shot to your import stations optimizations before we merge? Maybe you can adjust your parser so that it accepts the correct formatting? I'm up for that.

**Comment by ghost** [comment]
> @zacharyburnettNOAA Do you want to give another shot to your import stations optimizations before we merge? Maybe you can adjust your parser so that it accepts the correct formatting? I'm up for that.

sure, I'll work on that now, shouldn't take long

**Comment by ghost** [comment]
it was a misunderstanding on my part, I thought the `NOUTE`, `NOUTV`, etc. were the names of the number of stations, but that is actually `NSTAE`, `NSTAV`, etc. I updated the parser to reflect that.

**Comment by jreniel** [comment]
> it was a misunderstanding on my part, I thought the `NOUTE`, `NOUTV`, etc. were the names of the number of stations, but that is actually `NSTAE`, `NSTAV`, etc. I updated the parser to reflect that.

No problem, misunderstandings and bugs will always happen! We make science when we follow the evidence and observations, and adjust our work and understanding based off it. You are doing an excellent job!

**Comment by ghost** [comment]
do you also think it's a good idea to disable the Windows tests? I added them for completeness, but they take a long time, and I think we can assume that anything that runs in the Linux environment will also run on a correctly configured Windows environment as well

**Comment by jreniel** [comment]
> do you also think it's a good idea to disable the Windows tests? I added them for completeness, but they take a long time, and I think we can assume that anything that runs in the Linux environment will also run on a correctly configured Windows environment as well

Yes, the important tests are the interpreter versions, not so much the host OS. However, Windows wheel building is useful! And it would be cool to also do MacOS wheel building.

**Comment by ghost** [comment]
alright, I'll turn off the windows tests but keep it in the `build.yml`

**Pull request merged**
