### PR TITLE
Server config

### LINKED ISSUE #6: add class to generate shell script for server deployment of input files.

### PR DESCRIPTION
**Pull request by jreniel**

### CODE REVIEW

**Comment by jreniel** [comment]
@zacharyburnettNOAA I think we should only use type hinting in the public methods. If we use type hinting everywhere the code will become too verbose.

**Comment by jreniel** [comment]
Large scale code refactoring. The user interface doesn't change much but the internal data structures do.

**Comment by jreniel** [comment]
@zacharyburnettNOAA 462261c is my last commit for this round. Please take a look at it and let me know if you feel like we should merge this to master and bump the minor version number. Then we should open a new branch for expanding the unittests.

**Comment by ghost** [comment]
yes, it looks like these changes merit a new minor version

**Pull request merged**
