### PR TITLE
Update best_track.py

### PR DESCRIPTION
**Pull request by krober10nd**
* optional annotation of track times.

### CODE REVIEW

**Comment by krober10nd** [comment]
also would like to set an axis limit to the plot

**Comment by krober10nd** [comment]
If I'm plotting many tracks like this, I want to turn off track annotation. This PR just does that. 

top100mostintense

**Comment by jreniel** [comment]
@zacharyburnettNOAA Why is the codecov job failing?

**Comment by krober10nd** [comment]
Some research reveals that 

```
Codecov has some heisenberg issues. If you don't have a token, please add one otherwise try to:

Force-push to retrigger Codecov
Rotate your token.
```

https://stackoverflow.com/questions/67861379/codecov-fails-in-github-actions

**Comment by jreniel** [comment]
I vote ignoring this for now and merging anyway.
Any objections?  @zacharyburnettNOAA

**Comment by jreniel** [comment]
Guess what, rerunning the jobs solved it.

**Pull request merged**
