### PR TITLE
Fix netcdf issue for Hamtide tests

### LINKED ISSUE #188: Fix Hamtide
It seems that the updated netCDF4 package cannot work with the OPeNDAP link

### PR DESCRIPTION
**Pull request by SorooshMani-NOAA**
Tests that required Hamtide failed due to an issue with the latest version of netcdf library installed using pip. Fixes #188

### CODE REVIEW

**Comment by SorooshMani-NOAA** [comment]
@WPringle I tried to address a couple of issues for tests to run successfully in this PR locally everything works, but now I see errors in macos version! When I look at the diff (I outputted the diff in the test for debugging) I see some section of tides that are different from the reference (on linux on my machine it's fine).

If you're working on a mac can you please run tests and see what you get?

**Comment by WPringle** [comment]
@SorooshMani-NOAA On Argonne linux machine using python 3.10 I'm getting a failed test for `test_stations.py`

**Comment by SorooshMani-NOAA** [comment]
I had to update the station references. For some reason the order of stations changed (maybe due to a change in searvey or even server side).

Make sure you have the latest reference files for local testing. What about macos? Were you able to test on a mac?

**Comment by SorooshMani-NOAA** [comment]
Thanks to @AtiehAlipour-NOAA we ran the tests on a mac machine and we get a crash from `shapely`:

image

The run env was created by conda with `python=3.10`, `gdal` `netcdf4` and `hdf5` installed using `mamba`/`conda` and the rest of packages installed using `pip`. 
```
git clone https://github.com/oceanmodeling/adcircpy
cd adcircpy/
git checkout test/fix_hamtide_nc
mamba create -n adcircpytest -cconda-forge python=3.10 netcdf4 hdf5 gdal
conda activate adcircpytest
pip install -e .[testing]
pytest tests/
ls tests/data/output/
```

If we don't install `gdal` by `conda` we'll get an error:

image



On the CI for mac `brew` is used for netcdf and hdf, but the rest are installed by `pip`:

```bash
brew install hdf5
brew install netcdf
```

**Comment by SorooshMani-NOAA** [comment]
After more testing via updating tests and ref files it seems the reason behind the difference is how grid-data `linear` is results are different between mac and linux, but I'm not sure why! See code state at [82df7cd](https://github.com/oceanmodeling/adcircpy/pull/189/commits/82df7cd291b54e7c7cf3c124dcebd8804a905f08) where all calculations for point location and amp/phase are done within the test code.

**Pull request merged**
