### PR TITLE
use `pytest`

### PR DESCRIPTION
**Pull request by ghost**
replaced `unittest` with `pytest`, using `pytest` structures like bare `assert`, `pytest.fixture`, and `pytest-mock`

additionally, added the following for use in the github workflow:
- `pytest-cov` to utilize the `--cov` argument for coverage
- `pytest-xdist` to utilize the `--numprocesses` argument to run all tests on separate thread runners

### CODE REVIEW

**Comment by ghost** [comment]
it looks like the async tests take `2m 25s`to complete, down from `3m 31s`

**Comment by krober10nd** [comment]
It seems you're linting on all Python builds. Is this necessary? Probably could save some time avoiding that.

**Comment by krober10nd** [comment]
I'm wondering if it would somehow be possible to test the examples or make them testable. When your tests are your examples, it is less work and more likely for things to remain working then if they were not.

**Comment by krober10nd** [comment]
Maybe put them onto the README and use `pytest-codeblocks`?

**Comment by ghost** [comment]
> 
> 
> Maybe put them onto the README and use `pytest-codeblocks`?

that's a good idea, I'll look into that for the examples. We could probably even do that in this PR

**Comment by krober10nd** [comment]
Nice! Probably could also put a short paragraph above each example saying what it does.

**Comment by krober10nd** [comment]
Looks like a missing file

```
ERROR tests/test_best_track_run.py - FileNotFoundError: [Errno 2] No such fil...
120
```

**Comment by ghost** [comment]
i just need to fix the codeblocks in the README and then it should be good to go

**Comment by ghost** [comment]
for some reason the tests aren't passing on Linux, I'll try running on WSL

**Comment by ghost** [comment]
weird, `pytest` works just fine on my local WSL

**Comment by ghost** [comment]
looks like the tests are currently failing because github actions uses 2 processors but the reference files expect 4
```diff
- NPROCS=4
-   adcprep --np 4 --partmesh
-   adcprep --np 4 --prepall
-   mpiexec -n 4 punswan 2>&1 | tee ../punswan.log
-   mpiexec -n 4 punswan 2>&1 | tee -a ../punswan.log
+ NPROCS=2
+   adcprep --np 2 --partmesh
+   adcprep --np 2 --prepall
+   mpiexec -n 2 punswan 2>&1 | tee ../punswan.log
+   mpiexec -n 2 punswan 2>&1 | tee -a ../punswan.log
```

**Comment by ghost** [comment]
@krober10nd and @jreniel I will merge these changes into the `main` if you don't have any objections; mainly, I just added new reference files for the tests to check against, and fixed some minor errors

**Comment by krober10nd** [comment]
Looks like 3.9 is still failing maybe all versions of Python are trying to upload their codecov reports to the same location?  Not sure how to interpret that. Otherwise, it looks great.

**Review by krober10nd — APPROVED** [review]

**Comment by ghost** [comment]
> Looks like 3.9 is still failing maybe all versions of Python are trying to upload their codecov reports to the same location? Not sure how to interpret that. Otherwise, it looks great.

the codecov upload only triggers on the python 3.9 run, so that would be why. I'm not sure why the upload is failing specifically

**Review by jreniel — APPROVED** [review]

**Pull request merged**
