### PR TITLE
add formatted logger that splits output between `stdout` and `stderr`

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by krober10nd** [comment]
curious: how can/how does one access the logging information used?

**Comment by ghost** [comment]
> curious: how can/how does one access the logging information used?

the logger outputs to console and / or file, depending on how you set it up. This function basically just makes setup easier, and lets you inherit from an existing logger with dot notation in the name 
```python
logger_1 = get_logger('main_logger', log_filename='/path/to/logfile.txt', console_level=logging.DEBUG)
logger_2 = get_logger('main_logger.sub_logger', console_level=logging.INFO)

logger_1.warning('this will show in stderr')
logger_1.info('this will show in stdout')
logger_2.debug('this will not show')
```

**Comment by krober10nd** [comment]
I'm going to look at this next week, okay? I'm pretty busy now.

**Comment by ghost** [comment]
> I'm going to look at this next week, okay? I'm pretty busy now.

no problem, there's no rush

**Review by krober10nd — APPROVED** [review]
I think this is reasonable.

**Pull request merged**
