### PR TITLE
adding buffer command to make mesh envelope valid

### PR DESCRIPTION
**Pull request by WPringle**
Or can we remove this feature or make it more straightforward?

### CODE REVIEW

**Comment by WPringle** [comment]
Yeah I think better to remove this feature, until maybe the mesh boundary computation feature is improved.

**Comment by krober10nd** [comment]
If you have a polygonal boundary, you can create a `geodataframe`, project it to projection that makes sense, then add a buffer to the `geometry` field, and project back to geographic.

**Comment by ghost** [comment]
@WPringle which mesh has the invalid problem?

**Comment by WPringle** [comment]
@zacharyburnettNOAA The subsetted mesh. And then when I used the original old HSOFS mesh it only extracted two stations, which I do not think is correct.

**Comment by WPringle** [comment]
This kind of automated selection of stations that fits within the mesh seems like a good idea at first but sometimes it just ends up being annoying, because as a user you may expect to just get all the stations imported into the fort.15 but then when that doesn't happen it can be confusing. Second, sometimes if you make a mesh that only meshes the ocean side the station falls just outside the mesh but adcirc can still get a reasonable estimate for the station by taking the nearest vertex (automatically). Further, adcirc notes the user about which stations fall outside the mesh.  

Suggest that once the mesh boundary can be more correctly extracted for this operation, that we make this as a non-default option, i.e., the user should request this feature explicitly to invoke it.

**Comment by ghost** [comment]
> Suggest that once the mesh boundary can be more correctly extracted for this operation, that we make this as a non-default option, i.e., the user should request this feature explicitly to invoke it.

that makes sense, good idea.

**Comment by ghost** [comment]
implemented with 72c531d6a9b578a7940fa762880185da4d72852c

**Pull request merged**
