### PR TITLE
supporting NWS=8 in creating job script

### PR DESCRIPTION
**Pull request by WPringle**

### CODE REVIEW

**Comment by SorooshMani-NOAA** [comment]
@WPringle I haven't used ADCIRC in the last 8 years, so I can't comment on the validity of output, the change is very minimal, do you want me to review anything in specific?

**Comment by WPringle** [comment]
@SorooshMani-NOAA I know, it is a just minor change to put handle the line in job script when use NWS=8. I don't think anything to look at in particular, just to get an approve. But do we still have these online test problems?

**Comment by SorooshMani-NOAA** [comment]
Have you run the tests locally to see what is the change that is causing the problem? By the way since this is now on OceanModeling community, you should be able to merge without NOAA-side review as well.

**Comment by zacharyburnett** [comment]
https://github.com/oceanmodeling/adcircpy/actions/runs/6266155764/job/17016533648?pr=180#step:6:196
```
FAILED tests/test_stations.py::test_Stations - AssertionError: "tests/data/output/test_Stations/stations_2.fort.15" != "tests/data/reference/test_Stations/stations_2.fort.15"
```
it looks like the `fort.15` is also updated in this case

**Comment by SorooshMani-NOAA** [comment]
@zacharyburnett thanks for responding. I think what @WPringle is asking is about an issue we noticed at some point on some other repos where the tests were running successfully locally, but on GitHub it returned errors. That's why I'm asking if he already ran the tests on his machine

**Comment by zacharyburnett** [comment]
It appears that station `8665530` is reordered in all the categories:
```shell
diff ./tests/data/output/test_Stations/stations_1.fort.15 ./tests/data/reference/test_
Stations/stations_1.fort.15 
```
```diff
6a7
> -79.9236068725586 32.78083038330078                             ! 8665530                            
10d10
< -79.9236068725586 32.78083038330078                             ! 8665530                            
20a21
> -79.9236068725586 32.78083038330078                             ! 8665530                            
24d24
< -79.9236068725586 32.78083038330078                             ! 8665530                            
34a35
> -79.9236068725586 32.78083038330078                             ! 8665530                            
38d38
< -79.9236068725586 32.78083038330078                             ! 8665530                            
48a49
> -79.9236068725586 32.78083038330078                             ! 8665530                            
52d52
< -79.9236068725586 32.78083038330078                             ! 8665530                            
```

**Comment by SorooshMani-NOAA** [comment]
Thanks @zacharyburnett I get the same thing locally. @WPringle this change is harmless, right? The order doesn't matter in this case, does it? If it's so I can submit the updated order of stations and it should work fine for merge

**Comment by WPringle** [comment]
@SorooshMani-NOAA Sounds good to me thank you!

**Review by SorooshMani-NOAA — APPROVED** [review]

**Comment by SorooshMani-NOAA** [comment]
@brey I cannot push to this repo. Where can I check if I have the right permissions?  I don't see the Settings tab for this repo!

**Comment by brey** [comment]
@SorooshMani-NOAA I have added you. Try again.

**Comment by SorooshMani-NOAA** [comment]
The latest error seems to be due to `searvey` issue which is due to an update in `dataretrieval` package!

**Pull request merged**
